name: Run the script every hour

on:
  push:
  schedule:
    - cron: '0 0 1 1 *'  # Runs at 00:00, on day 1 of the month, only in January.
    
jobs:
    build:
      runs-on: ubuntu-latest
      name: Run Script
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
        - uses: browser-actions/setup-chrome@v1
        - uses: nanasess/setup-chromedriver@v2
        - run: bundler install
        - run: ./script.rb
          env:
            SO_EMAIL: ${{secrets.SO_EMAIL}}
            SO_PASSWORD: ${{secrets.SO_PASSWORD}}
