on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
    build:
      runs-on: ubuntu-16.04
      name: Run Script
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'
        - uses: browser-actions/setup-chrome@v1
        - run: chrome --version
        - name: Install Deps
          run: gem install tanakai
        - name: Run script
          run: ruby -e "puts Date.today.to_s"
          env:
            SO_EMAIL: ${{secrets.SO_EMAIL}}
            SO_PASSWORD: ${{secrets.SO_PASSWORD}}
